---
- name: Install Oracle Client 19c on Windows Server 2022
  hosts: windows
  tasks:
    - name: Create Oracle user
      win_user:
        name: oracle
        password: 'YourSecurePassword'
        groups:
          - Administrators
        state: present

    - name: Download Oracle Client 19c
      win_get_url:
        url: 'https://download.oracle.com/otn_software/nt/instantclient/instantclient-basic-windows.x64-19.9.0.0.0dbru.zip'
        dest: 'C:\\temp\\instantclient-basic-windows.x64-19.9.0.0.0dbru.zip'

    - name: Unzip Oracle Client 19c
      win_unzip:
        src: 'C:\\temp\\instantclient-basic-windows.x64-19.9.0.0.0dbru.zip'
        dest: 'C:\\oracle\\instantclient_19_9'
        creates: 'C:\\oracle\\instantclient_19_9\\sqlplus.exe'

    - name: Set Oracle environment variables
      win_environment:
        state: present
        name: '{{ item.name }}'
        value: '{{ item.value }}'
      with_items:
        - { name: 'ORACLE_HOME', value: 'C:\\oracle\\instantclient_19_9' }
        - { name: 'PATH', value: 'C:\\oracle\\instantclient_19_9;%PATH%' }