name: Deploy Stack on aws by using creds 
on: 
  push:
    branches:
      - main  # when ever any code to pushed to main branch, it will trigger the pipeline

jobs:  # we are creating jobs to perform steps
  s3-deploy:
    runs-on: ubuntu-latest # from azure pool
    steps: # steps to setup cdk and run code
    - name: setup node.js 20 version
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: checkout git repo code to vm
      uses: actions/checkout@v2

    - name: verify code in vm
      run: ls

    - name: install dependencies
      run: |
        cd szhou-day4-bestway
        npm install
        npm install -g aws-cdk
    - name: compile code
      run: |
        cd szhou-day4-bestway
        cdk synth
    - name: deploy cdk in aws account
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        cd szhou-day4-bestway/
        cdk deploy SzhouDay4BestwayStack --require-approval never

  ec2-deploy:
    runs-on: ubuntu-latest # from azure pool
    needs: s3-deploy # it will run after s3-deploy job

    steps: # steps to setup cdk and run code
    - name: setup node.js 20 version
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: checkout git repo code to vm
      uses: actions/checkout@v2

    - name: verify code in vm
      run: ls

    - name: install dependencies
      run: |
        cd szhou-day4-bestway
        npm install
        npm install -g aws-cdk
    - name: compile code
      run: |
        cd szhou-day4-bestway
        cdk synth
    - name: deploy cdk in aws account
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        cd szhou-day4-bestway/
        cdk deploy SzhouDay4Ec2all --require-approval never
